title: Tyler Hilker
email: email@example.com
description: Tyler Hilker's personal website
url: "https://tylerhilker.com"
twitter: thehilker

baseurl: ""
permalink: /:categories/:title:output_ext
markdown: kramdown
plugins:
  - jekyll-feed
